---
title: "Chicago Equality"
author: "Sofia Marie Mascia"
date: "04/12/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(shiny)
library(shinydashboard)
library(tidyverse)
library(stringr)
library(ggplot2)
library(dplyr)
library(base)
library(devtools)
library(urbnmapr)
library(plotly)
library(RColorBrewer)

```

```{r}
data <- read.csv("chicago-inequality.csv", na.strings=c(""," ","NA"))
```

```{r}
#Here I clena the data that will be used in my Homicide bar graph

clean_data <- data %>% 
  drop_na(geo_name) %>% 
  select(geo_name, homicide_rate_2015, 
         homicide_rate_2016, income_2015, income_2016) %>% 
  group_by(geo_name) %>% 
  mutate(state = str_sub(geo_name, -2, -1)) %>% 
  filter(state == "IL") %>% 
  mutate_all(funs(replace(., is.na(.), 0))) %>% 
  filter(homicide_rate_2015 >= 3, homicide_rate_2016 >= 3) %>% 
  mutate(County = geo_name)

 ## Later - find a way to clean county column: str_split(geo_name, "County, ", n=2)

 clean_data %>% write_rds("demo_app/chicago_inequality.rds")
```


```{r}

#Cleaning data for income map

#INCOME WHITE
income_white <- read.csv("income_white.csv", na.strings=c(""," ","None"))

income_white <- income_white %>% 
  filter(year == 2015) %>% 
  mutate(county_fips = str_sub(geo, 8, 12)) %>% 
  select(income_white, county_fips) %>% 
  mutate_all(funs(replace(., is.na(.), 0)))
  
  income_white %>% write_rds("demo_app/income_white.rds") 


#INCOME BLACK
income_black <- read.csv("income_black.csv", na.strings=c(""," ","None"))

income_black <- income_black %>% 
  filter(year == 2015) %>% 
  mutate(county_fips = str_sub(geo, 8, 12)) %>% 
  select(income_black, county_fips) %>% 
  mutate_all(funs(replace(., is.na(.), 0)))

income_black %>% write_rds("demo_app/income_black.rds")


#INCOME HISP
income_hisp <- read.csv("income_hisp.csv", na.strings=c(""," ","None"))

income_hisp <- income_hisp %>% 
  filter(year == 2015) %>% 
    mutate(county_fips = str_sub(geo, 8, 12)) %>% 
   select(income_hispanic, county_fips) %>% 
   mutate_all(funs(replace(., is.na(.), 0)))

income_hisp %>% write_rds("demo_app/income_hisp.rds")

white_black <- left_join(income_white, income_black, by = "county_fips")

white_black_hisp <- left_join(white_black, income_hisp, by = "county_fips")

```

```{r}

## Loading County Data
## Note this data was accessed by loading the "urbnmapr" package from github: 
  # LINK : 

household_data <- left_join(countydata, counties, by = "county_fips") 

mapping_data <- household_data %>% 
  filter(state_name == "Illinois") %>%
  filter(year == "2015") %>% 
  mutate(group = as.numeric(group)) %>% 
  mutate(piece = as.numeric(piece))
  
  
race_mapping_data <- left_join(white_black_hisp, mapping_data, by = "county_fips")

race_mapping_data <- race_mapping_data %>% 
  mutate(county_fips = as.integer(county_fips)) 

race_mapping_data %>% write_rds("demo_app/race_mapping_data.rds")




```

```{r}
#Cleaning Data for My Poverty and Race table

poverty_race <- read.csv("poverty_race.csv", na.strings=c(""," ","None"))

poverty_race <- poverty_race %>% 
  select(year, poverty_white, poverty_asian, poverty_black, poverty_hispanic, poverty_other) %>% 
  mutate(total_pov = poverty_white + poverty_asian + poverty_black + poverty_hispanic + poverty_other) %>%
  group_by(year) %>% 

  gather(poverty_white, poverty_asian, poverty_black, poverty_hispanic, poverty_other, key = "race", value = "total_race") %>% 
  mutate(share = (total_race/total_pov)*100) %>%

  mutate(race = case_when(
    race == "poverty_white" ~ "White",
    race == "poverty_asian" ~ "Asian",
    race == "poverty_black" ~ "Black",
    race == "poverty_hispanic" ~ "Hisp",
    race == "poverty_other" ~ "Other"))


poverty_race %>% write_rds("demo_app/poverty_race.rds")

```



